/* eslint-disable quote-props */
/* eslint-disable max-len */
/**
 * Translation file for this resource.
 *
 * This file is generated by combining automatic extraction and manual translations:
 * - The "en" (English) section is automatically extracted from source files
 * - Other language sections can be manually translated or pulled from Transifex
 * - When regenerating, existing manual translations are preserved when the English
 *   source text hasn't changed
 *
 * Structure:
 * - interface: translations for name/description (used by GUI formatMessage)
 * - extensions: translations for extension blocks (used by VM formatMessage)
 * - blocks: translations for Blockly blocks (used by Blockly.Msg)
 */
export default {
    'interface': {
        'en': {
            'insertSourceCode.description': 'Insert the source code directly into the blocks, so that professional users can realize some more advanced functions.',
            'insertSourceCode.name': 'Insert Source Code'
        },
        'ru': {
            'insertSourceCode.description': 'Insert the source code directly into the blocks, so that professional users can realize some more advanced functions.',
            'insertSourceCode.name': 'Insert Source Code'
        },
        'zh-cn': {
            'insertSourceCode.description': 'Insert the source code directly into the blocks, so that professional users can realize some more advanced functions.',
            'insertSourceCode.name': 'Insert Source Code'
        },
        'zh-tw': {
            'insertSourceCode.description': 'Insert the source code directly into the blocks, so that professional users can realize some more advanced functions.',
            'insertSourceCode.name': 'Insert Source Code'
        }
    },
    'extensions': {},
    'blocks': {}
};
